
[ingame]
	#Range: 1 ~ 10
	long_press_count = 3
	auto_preparation = true
	mining_autoswitch_items = []
	show_target_indicator = true
	#Range: 0.0 ~ 1.0
	laser_pointer_color = 0.328125
	enable_laser_pointer = true
	#Allowed Values: NONE, HURT, TARGET
	health_bar_show_option = "HURT"
	camera_auto_switch = false
	filter_animation = true
	off_gore = false
	no_mining_in_combat = true
	battle_autoswitch_items = ["ars_nouveau:enchanters_shield", "ars_nouveau:enchanters_sword", "ars_nouveau:spell_bow", "ars_nouveau:spell_crossbow", "copperarmorandtools:coppersword", "copperarmorandtools:exposedsword", "copperarmorandtools:oxidizedsword", "copperarmorandtools:waxedsword", "copperarmorandtools:weatheredsword", "epicfight:diamond_dagger", "epicfight:diamond_greatsword", "epicfight:diamond_longsword", "epicfight:diamond_spear", "epicfight:diamond_tachi", "epicfight:golden_dagger", "epicfight:golden_greatsword", "epicfight:golden_longsword", "epicfight:golden_spear", "epicfight:golden_tachi", "epicfight:iron_dagger", "epicfight:iron_greatsword", "epicfight:iron_longsword", "epicfight:iron_spear", "epicfight:iron_tachi", "epicfight:knuckle", "epicfight:netherite_dagger", "epicfight:netherite_greatsword", "epicfight:netherite_longsword", "epicfight:netherite_spear", "epicfight:netherite_tachi", "epicfight:stone_greatsword", "epicfight:stone_spear", "epicfight:uchigatana", "hexerei:warhammer", "immersiveengineering:shovel_steel", "immersiveengineering:sword_steel", "minecraft:bow", "minecraft:crossbow", "minecraft:diamond_sword", "minecraft:golden_sword", "minecraft:iron_sword", "minecraft:netherite_sword", "minecraft:shield", "minecraft:stone_sword", "minecraft:trident", "minecraft:wooden_sword", "starbunclemania:star_sword", "quark:pickarang", "wom:agony", "wom:antitheus", "wom:diamond_greataxe", "wom:golden_greataxe", "wom:iron_greataxe", "wom:netherite_greataxe", "wom:tormented_mind", "wom:netherite_staff", "wom:diamond_staff", "wom:golden_staff", "wom:iron_staff", "wom:stone_staff", "wom:wooden_staff", "wom:moonless", "wom:herrscher", "wom:ender_blaster", "wom:gesetz", "wom:satsujin"]

	[ingame.ui]
		#Allowed Values: LEFT, RIGHT, CENTER
		stamina_bar_x_base = "RIGHT"
		weapon_innate_x = 42
		weapon_innate_y = 48
		charging_bar_y = 60
		#Allowed Values: LEFT, RIGHT, CENTER
		weapon_innate_x_base = "RIGHT"
		charging_bar_x = -119
		#Allowed Values: HORIZONTAL, VERTICAL
		passives_align_direction = "HORIZONTAL"
		#Allowed Values: TOP, BOTTOM, CENTER
		charging_bar_y_base = "CENTER"
		#Allowed Values: LEFT, RIGHT, CENTER
		passives_x_base = "RIGHT"
		passives_y = 36
		#Allowed Values: TOP, BOTTOM, CENTER
		passives_y_base = "BOTTOM"
		stamina_bar_x = 120
		#Allowed Values: TOP, BOTTOM, CENTER
		stamina_bar_y_base = "BOTTOM"
		stamina_bar_y = 10
		passives_x = 70
		#Allowed Values: TOP, BOTTOM, CENTER
		weapon_innate_y_base = "BOTTOM"
		#Allowed Values: LEFT, RIGHT, CENTER
		charging_bar_x_base = "CENTER"

