
[types]

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

[entries]

	[entries.wood_type]

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			roof = true
			planks_attic_roof = true
			upper_lower_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwwindows]
			plank_window = true
			louvered_shutter = true
			plank_window2 = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			four_window = true
			blinds = true
			plank_parapet = true
			window = true
			shutter = true
			stripped_log_window = true
			pane_window = true
			plank_pane_window = true
			stripped_pane_window = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			horse_fence = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			hollow_log = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

